[package]
name = "rumbledome-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "JSON/CLI protocol definitions for RumbleDome"

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true