name: Build RumbleDome Manifest to assist AI when processing the repo

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.rd-manifest.json'   # prevent self-trigger loops
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # full history for timestamps & SHAs
          persist-credentials: true

      - name: Generate manifest
        shell: bash
        run: |
          set -euo pipefail
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          COMMIT="${{ github.sha }}"
          DATE="$(git show -s --format=%cI "${COMMIT}")"

          # Only tracked files (no .git, no build artifacts)
          mapfile -t FILES < <(git ls-files | sort)

          tmp=".rd-manifest.json.tmp"
          {
            echo '{'
            echo "  \"repo\": \"${REPO}\","
            echo "  \"commit\": \"${COMMIT}\","
            echo "  \"branch\": \"${BRANCH}\","
            echo "  \"generated_at\": \"${DATE}\","
            echo '  "files": ['
          } > "$tmp"

          first=1
          for f in "${FILES[@]}"; do
            # Skip the manifest itself
            [ "$f" = ".rd-manifest.json" ] && continue
            raw_path="$(printf '%s' "$f" | sed 's/ /%20/g; s/#/%23/g')"
            raw_url="https://raw.githubusercontent.com/${REPO}/${BRANCH}/${raw_path}"
            sha="$(git ls-files -s -- "$f" | awk '{print $2}')"
            [ -z "$sha" ] && continue

            if [ $first -eq 0 ]; then echo ',' >> "$tmp"; fi
            first=0
            printf '    { "path": "%s", "raw": "%s", "sha": "%s" }' \
              "$f" "$raw_url" "$sha" >> "$tmp"
          done

          {
            echo
            echo '  ]'
            echo '}'
          } >> "$tmp"

          cat "$tmp" | jq .  # pretty-print to validate

          # Write only if changed
          if [ ! -f .rd-manifest.json ] || ! cmp -s "$tmp" .rd-manifest.json; then
            mv "$tmp" .rd-manifest.json
          else
            rm -f "$tmp"
            echo "Manifest unchanged."
          fi

      - name: Commit manifest if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .rd-manifest.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: add/update .rd-manifest.json"
            git push
          fi